config/routes.rb
Rails.application.routes.draw do
 
 devise_for :users
 root 'blogs#index' #一覧表示
 get '/new' => 'blogs#new' #投稿画面
 post '/complete' => 'blogs#create' #投稿機能
 post '/login' => 'blogs#login' #ログイン画面
 delete '/:id' => 'blogs#destroy' #削除機能
 get '/:id/edit' => 'blogs#edit' #編集画面
 patch '/:id' => 'blogs#update' #編集機能
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader
    #has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    before_action :move_to_index, except: :index
    
    def index
        flash[:notice] = "ようこそ。本日は#{Date.today}です。"
        @article =Article.order("updated_at DESC").page(params[:page]).per(5)
    end
    
    def new
        @article = Article.new
    end
    
    def create
        # binding.pry
        @article = Article.create(title: blog_params[:title], image: blog_params[:image], content: blog_params[:content], user_id: current_user[:id])
     if @article.save
      # メッセージの保存に成功した場合
      redirect_to action: :index, notice: 'メッセージの送信に成功しました'
     else
      # メッセージの保存に失敗した場合
      redirect_to action: :new, notice: 'メッセージの送信に失敗しました'
     end
    end
    
    def destroy
        article = Article.find(params[:id])
        article.destroy if article.user_id == current_user.id
    end
    
    def edit
        @article = Article.find(params[:id])
    end
    
    def update
        article = Article.find(params[:id])
        article.update(blog_params) if article.user_id == current_user.id
    end
    
    private
    def blog_params
        params.require(:article).permit(:title, :image, :content)
    end
        
    def move_to_index
        redirect_to action: :index unless user_signed_in?
    end    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/hoges_helper.rb
module HogesHelper
end

app/views/blogs/create.html.erb
<div class="contents row">
    <div class="success">
        <h3>
            投稿が完了しました。
        </h3>
        <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
</div>

app/views/blogs/destroy.html.erb
<p>削除しました</p>
<%= link_to '一覧へ戻る/', "/" %>

app/views/blogs/edit.html.erb
<div class="contents row">
    <a href="/">一覧に戻る</a>
    <%= form_tag("/#{@article.id}", method: :patch) do %>
     <h3>
         編集する
     </h3>
     <p><input type="text" name="title" placeholder="タイトル" value="<%= @article.title %>"></p>
     <p><input type="text" name="image" placeholder="Image url" value="<%= @article.image %>"></p>
     <textarea name="content" placeholder="記事を編集してください" rows="10" cols="50"><%= @article.content %></textarea>
     <p><input type="submit" value="投稿"></p>
    <% end %>
</div>

app/views/blogs/index.html.erb
<% flash.each do |key, value| %>
 <%= content_tag(:div, value, class: "#{key}") %>
<% end %>
 
<ul class="list_article">
  <% @article.each do |article| %>
  <div class="article_set">
  <li>
    <h2><%= article.title %></h2>
    <div class="article_post">
    <% if article.image !="" %>
    
     <p><img src="<%= article.image %>"></p>
    </div>
    <% end %>
    <p><%= article.content %></p>
    <p><%= fa_icon("clock-o") %><%= article.created_at.strftime("%Y-%m-%d %H:%M") %></p>
  </li>
 
  <% if user_signed_in? %>
   <div class="edit_tag">
   <ul>
     <li><%= link_to '編集', "/#{article.id}/edit", method: :get %></li>
     <li><%= link_to '削除', "/#{article.id}", method: :delete %> </li>
   </ul>
   </div>
  </div>
   <% end %>

<% end %>
<%= paginate(@article) %>
</ul>

app/views/blogs/new.html.erb
<div class ="contents_row">
    <a href="/">一覧に戻る</a>
   <div class="field">

    <%= form_for @article, url: complete_path  do |f| %>
         
         <p><%= f.text_field :title, :placeholder =>"タイトル" %></p>
         
         <p><%= f.file_field :image, :placeholder =>"ファイルを選択して下さい" %></p>
         
         <p><%= f.text_area :content, :placeholder =>"コメントを書いて下さい",size: "50x8" %></p>
         <p><%= f.submit "送信" %></p>
    <% end %>
   </div>
</div>     
    <!--%= form_tag('/complete', method: :post) do %>-->
    <!-- <h3>-->
    <!--     投稿する-->
    <!-- </h3>-->
    <!-- <p><input type="text" name="title" placeholder="タイトル"></p>-->
    <!-- <p><input type="text" name="image" placeholder="Image Url"></p>-->
    <!-- <textarea name="content" placeholder="記事を書いてください" rows="13" cols="50"></textarea>-->
     
    <!-- <p><input type="submit" value="投稿"></p>-->
     
     
     
    <!--% end %>-->
<!--</div>-->

app/views/blogs/update.html.erb
<p>更新しました</p>
<%= link_to '一覧へ戻る/', "/" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>燈穂君の成長日記</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="http://fonts.googleapis.com/css?family=Paytone+One" rel="stylesheet" type="text/css">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class ="header" >
      <div class="title">
       <a href ="/">燈穂君の成長日記</a>
      </div>
     <% if user_signed_in? %>
     <div class="nav">
       <a href="/new">新規投稿</a>
       <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
     </div>
      <!-- <div class="name">ようこそユーザー:<%= current_user.nickname %>さん</div> -->
     <% else %>
     <div class ="new">
       <%= link_to "ログイン", new_user_session_path, class: 'post' %>
       <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
     </div>
     <% end %>
     
    </div>
    <%= yield %>
  </body>
</html>